issue#185  高精度问题
alibaba/QLExpress pull request #186
Opened 2022-03-19 05:56 UTC by taokan

如果高精度溢出，超出Long范围值计算变成BigDecimal，其余保留原始逻辑

2022-03-19 05:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/QLExpress?pullRequest=186) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/QLExpress?pullRequest=186) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/QLExpress?pullRequest=186) it.</sub>

2022-03-20 06:50 UTC, DQinYuan requested changes

2022-03-20 06:50 UTC, DQinYuan commented on src/main/java/com/ql/util/express/OperatorOfNumber.java
> +            if(number.compareTo(new BigDecimal(Integer.MAX_VALUE)) < 1 && number.compareTo(new BigDecimal(Integer.MIN_VALUE)) > -1){
Integer.MAX_VALUE Integer.MIN_VALUE Long.MAX_VALUE Long.MIN_VALUE

这些 BigDecimal 是不是应该考虑作为单例，而不是每次都新建？

2022-03-20 07:26 UTC, taokan commented on src/main/java/com/ql/util/express/OperatorOfNumber.java
> +            if(number.compareTo(new BigDecimal(Integer.MAX_VALUE)) < 1 && number.compareTo(new BigDecimal(Integer.MIN_VALUE)) > -1){
改成静态变量，避免每次调用new一个新对象

2022-03-20 07:33 UTC, DQinYuan commented
LGTM

2022-03-20 07:34 UTC, DQinYuan approved these changes
LGTM

2022-03-20 13:11 UTC, merged