4.0.0 utils
alibaba/QLExpress pull request #191
Opened 2022-04-09 10:07 UTC by taokan

4.0.0
utils -- BasicUtils\ExpressUtil\PropertiesUtils\QLAliasUtils

remove common beans Utils
new add:
1.get instance field classType
2.get instance field Value
3.set instance field
4.get static field value
5.get method

new add cache strategy
[useCacheClear] default:false
when cut-off is true release cache out of the mem

2022-04-10 09:48 UTC, DQinYuan requested changes

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/utils/PropertiesUtils.java
> +            if (accessMember instanceof Method) {
accessMember 已经是 null，这个判断始终是 false

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/utils/PropertiesUtils.java
> +            }else if(accessMember instanceof Field){
accessMember 已经是 null，这个判断始终是 false

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/utils/PropertiesUtils.java
> +            if (accessMember instanceof Method) {
始终为 false

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/utils/PropertiesUtils.java
> +            }else if(accessMember instanceof Field){
始终为 false

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MemberHandler.java
> +        public static Member getAccessMember(Class clazz, String property, AccessMode propertyMode, boolean isStaticCheck) {
注意一下和 apache common bean utils 的特性保持一致。我记得 apache 是先取 getter，再取 field？这里是不是反了。

https://commons.apache.org/proper/commons-beanutils/apidocs/index.html?org/apache/commons/beanutils/PropertyUtilsBean.html

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/utils/BasicUtils.java
> +        char[] c = s.toCharArray();
为什么要先搞个字符数组，然后拷贝，直接 StringBuilder 不是更好吗，代码也更好理解一点

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/utils/BasicUtils.java
> +    public static String getSetter(String s) {
为什么要先搞个字符数组，然后拷贝，直接 StringBuilder 不是更好吗，代码也更好理解一点

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/utils/BasicUtils.java
> +    public static String getIsGetter(String s) {
同上

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/utils/PropertiesUtils.java
> +     * get instance field classType (accessField and getMethod)
注释上标明下，如果返回 null，表示找不到该属性

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MemberHandler.java
> +                f = clazz.getField(property);
可能要特殊处理下  .class .length 属性，记得加在单元测试中

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +        String simpleIsGet = IS_SIGN + property;
这里的 simpleIsGet 不符合 Java Bean 规范，不应该考虑它

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +    public static Method getGetter(Class clazz, String property, boolean isStaticCheck) {
这里用 Class<?> 作签名更好

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +        String simple = GET_SIGN + property;
这里的 simple 不符合 Java Bean 规范，不应该考虑它

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +        if (Collection.class.isAssignableFrom(clazz) && IS_EMPTY.equals(isGet)) {
isEmpty 为何要单独处理？

2022-04-10 09:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +        Map<String, Integer> map = new HashMap<>();
这里写的过于复杂，getter 没这么多，理论上只有一种，boolean 的情况下是 isXxx，非 bool 是 getXxx，不要写得这么复杂，很难懂

2022-04-10 11:47 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/utils/PropertiesUtils.java
> +            if (accessMember instanceof Method) {
bug  -- accessMember != null

2022-04-10 11:48 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/utils/PropertiesUtils.java
> +            }else if(accessMember instanceof Field){
同上

2022-04-10 11:48 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/utils/PropertiesUtils.java
> +            if (accessMember instanceof Method) {
同上

2022-04-10 11:48 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/utils/PropertiesUtils.java
> +            }else if(accessMember instanceof Field){
同上

2022-04-10 11:48 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/utils/PropertiesUtils.java
> +     * get instance field classType (accessField and getMethod)
ok

2022-04-10 11:51 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/member/MemberHandler.java
> +                f = clazz.getField(property);
.class .length 的处理在expressUtil中，单测我补下

2022-04-10 11:51 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +    public static Method getGetter(Class clazz, String property, boolean isStaticCheck) {
ok

2022-04-10 11:55 UTC, DQinYuan requested changes

2022-04-10 11:55 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +                    synchronized (accessMethod) {
这里不建议加锁，apache common beans 最大的问题就是取方法会加锁，容易导致很多线程锁在这里，这里我建议可以在 QLOptions 中加一个选项 “是否允许访问私有方法”，默认不允许访问，无锁，用户打开的情况下再将加一把锁

2022-04-10 11:55 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +                synchronized (accessMethod) {
同上

2022-04-10 11:55 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/config/QLExpressRunStrategy.java
> +public class QLExpressRunStrategy {
QLExpressRunStrategy 是 QLExpress4 中计划淘汰掉的一个类。这种静态全局的配置会带来很多限制，QLExpress 中使用的是更加灵活的 QLOptions

2022-04-10 11:55 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/utils/BasicUtils.java
> +    public static final Class<?>[][] CLASS_MATCHES = new Class[][] {
写好几个基础工具就可以了，这些代码就不用搬过来了，这些代码写得很差，bug 也很多

2022-04-10 11:59 UTC, DQinYuan commented
在 PR 里说明一下你这些工具类，哪些是入口方法，不然看着比较乱，很多都是 public 方法。老代码就不要搬了，那些老代码质量堪忧，估计也不会去用

2022-04-10 12:10 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/utils/BasicUtils.java
> +    public static final Class<?>[][] CLASS_MATCHES = new Class[][] {
好的，先留着，到时候没有用了删掉

2022-04-10 12:19 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +                    synchronized (accessMethod) {
好～

2022-04-10 12:40 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/member/MemberHandler.java
> +        public static Member getAccessMember(Class clazz, String property, AccessMode propertyMode, boolean isStaticCheck) {
fix 先取getter

2022-04-10 12:40 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +        String simpleIsGet = IS_SIGN + property;
ok

2022-04-10 12:45 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/config/QLExpressRunStrategy.java
> +public class QLExpressRunStrategy {
QLOptions 后面的设计是怎么获取呢

2022-04-21 01:50 UTC, DQinYuan requested changes

2022-04-21 01:50 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/cache/EdenCache.java
> +public class EdenCache<K,V> implements ICache<K,V> {
可以注明下这个 cache 的思想来自于哪里

2022-04-21 01:50 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetFieldInstruction.java
> +            throw errorReporter.report("GET_FIELD_INPUT_BEAN_NULL","input parameters is null");
错误文案感觉不太合适，看一下 Java 的，应该类似于 can not get field from null

2022-04-21 01:50 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetFieldInstruction.java
> +            throw errorReporter.report("GET_FIELD_VALUE_ERROR","InvocationTargetException: "+e.getMessage());
不要直接把 java 的 message 和异常名称暴露给用户，我们是不同于 Java 的另一种语言。那不属于QLE的语言规范

2022-04-21 01:50 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetFieldInstruction.java
> +        Object bean = parameters.get(0).get();
Parameters参数我会删除掉，调用 qRuntime.pop()

2022-05-15 08:37 UTC, DQinYuan requested changes

2022-05-15 08:37 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataMethodLambda.java
> +        }catch (Exception e){
这个异常不应该吃掉

2022-05-15 08:37 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataMethodLambda.java
> +public class DataMethodLambda implements QLambda {
这个命名感觉以 Data 开头不太妥

2022-05-15 08:37 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/MethodInvokeInstruction.java
> +        Parameters parameters = qRuntime.pop(0);
最新的分支上 QRuntime 已经有只弹出一个元素的 pop 方法了，调用哪个方法

2022-05-15 08:37 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/MethodInvokeInstruction.java
> +                qRuntime.push((Value) cacheElement);
这个指令的含义是把方法执行的结果的结果压到栈上，而不是把方法本身

2022-05-15 08:37 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetFieldInstruction.java
> +                CacheUtils.setFieldCacheElement(clazz, this.fieldName, dataField);
不能按照 LeftValue 粒度缓存，应该只缓存Field，因为 LeftValue 还保存了 bean，需要每个实例配个缓存，这样容易导致缓存过大，且命中率低

2022-05-15 08:37 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/cache/MethodCacheElement.java
> +        METHOD_CACHE = CacheFactory.cacheBuilder(size,isUseCacheClear);
方法和Field的缓存还是统一都用 LongTermCache 吧，因为方法和字段数是有限的，脚本缓存可以考虑使 EdenCache

2022-05-15 10:20 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetMethodInstruction.java
> +                    methods = PropertiesUtils.getMethod(bean, methodName, qlOptions.isAllowAccessPrivateMethod());
Java和QLExpress中都有一个特性，从实例中也可以获取类成员/方法，因此在获取不到实例方法时，还应该尝试通过 bean.getClass() 再获取一次类成员/方法

2022-05-15 10:20 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetFieldInstruction.java
> +                    getCacheFieldValue(qlOptions,(Class<?>) bean, bean, qRuntime);
Java和QLExpress中都有一个特性，从实例中也可以获取类成员/方法，因此在获取不到实例方法时，还应该尝试通过 bean.getClass() 再获取一次类成员/方法

2022-05-25 12:44 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataArray.java
> +public class DataArray implements Value {
统一成 DataValue

2022-05-25 12:44 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataClazz.java
> +public class DataClazz implements Value {
统一成 DataValue

2022-05-25 12:44 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataMethod.java
> +public class DataMethod implements Value {
统一成 DataValue

2022-05-25 12:44 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataMethodInvoke.java
> +public class DataMethodInvoke implements Value {
不需要

2022-05-30 07:38 UTC, DQinYuan requested changes

2022-05-30 07:38 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +                    || property.equals(method.getName())
方法名和属性名相同的情况应该不符合 JavaBean 规范吧，不应该考虑这种情况。把这种情况去掉后，代码应该可以简化不少，目前写得有点复杂了

2022-05-30 07:38 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/lambda/QLambdaMethod.java
> +            throw this.errorReporter.report("GET_METHOD_VALUE_ERROR", "can not get method value: " + e.getMessage());
这个异常不应该在这里 catch，应该抛出去，让调用的地方用调用处的 errorReporter 来报告错误。

举例：

```
m = Math::abs;
m.abs('aaaa', 'bbb')
```

上面代码的报错应该报错在第2行，而不是第1行。call 方法应该 throw exception的，我在 dev 上加一下

2022-05-30 07:38 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/cache/MethodCacheElement.java
> +            if (clazz == null) {
如果是方法签名，正常类型是不可能为 null 的

2022-05-30 07:38 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/cache/MethodCacheElement.java
> +            builder.append(",");
用 StringJoiner 或者 Collectors.joining

2022-05-30 07:38 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetMethodInstruction.java
> +                QLambda qLambda = new QLambdaMethod((List<Method>) cacheElement, bean, qlOptions.enableAllowAccessPrivateMethod(), this.errorReporter);
errorReporter 不应该从这里传过去，应该使用调用处的 errorReporter 报告异常。

2022-05-30 07:38 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +            for (Class<?> anInterface : interfaces) {
我记得 getDeclaredMethods 就已经能够获取到实现的接口方法了，应该没必要再调用 getInterfaces 遍历接口了，建议做个实验，删掉这部分代码

2022-05-30 07:38 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetMethodInstruction.java
> +            throw this.errorReporter.report("GET_METHOD_ERROR", "can not get method: " + e.getMessage());
同 GetFieldInstruction, try catch 太大了，这个 message 是否适合暴露给用户？

2022-05-30 07:44 UTC, DQinYuan requested changes

2022-05-30 07:44 UTC, DQinYuan commented on src/test/java/com/alibaba/qlexpress4/test/instruction/TestFieldInstruction.java
> +    public static void main(String[] args) {
不要用 main 函数写测试

2022-05-30 07:44 UTC, DQinYuan commented on src/test/resources/log4j.properties
>  log4j.appender.file.File=Test_LOG4j.log
为什么测试目录里有个 log4j 文件？

2022-05-30 07:44 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/cache/MethodCacheElement.java
> +    public Object getCacheElement(String key) {
ICacheElement 是否可以考虑加个泛型，ICacheElement<T>，然后

MethodCacheElement implements ICacheElement<Method>

这样就不用到处都是 Object

2022-06-04 05:04 UTC, DQinYuan requested changes

2022-06-04 05:04 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataValue.java
> +    private Object value;
这里可以是 final

2022-06-05 01:53 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/cache/MethodCacheElement.java
> +    public Object getCacheElement(String key) {
fix

2022-06-05 01:54 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataValue.java
> +    private Object value;
fix

2022-06-05 01:54 UTC, taokan commented on src/test/resources/log4j.properties
>  log4j.appender.file.File=Test_LOG4j.log
这个是以前QLE里面的

2022-06-05 01:54 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataMethod.java
> +public class DataMethod implements Value {
fix

2022-06-05 01:54 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetFieldInstruction.java
> +                    Value dataClazz = new DataClazz((Class<?>) bean);
fix

2022-06-05 01:55 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetFieldInstruction.java
> +                Value dataArray = new DataArray((Object[]) bean);
fix

2022-06-05 02:38 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/cache/MethodCacheElement.java
> +            builder.append(",");
fix

2022-06-05 02:38 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/cache/MethodCacheElement.java
> +            if (clazz == null) {
fix

2022-06-05 02:45 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/lambda/QLambdaMethod.java
> +            throw this.errorReporter.report("GET_METHOD_VALUE_ERROR", "can not get method value: " + e.getMessage());
unfix

2022-06-05 02:46 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetMethodInstruction.java
> +                QLambda qLambda = new QLambdaMethod((List<Method>) cacheElement, bean, qlOptions.enableAllowAccessPrivateMethod(), this.errorReporter);
fix

2022-06-05 03:06 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +            for (Class<?> anInterface : interfaces) {
验证了不能删掉

2022-06-05 03:07 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataField.java
> +        Object rs = methodGet();
在methodGet里面加了判断如果取不到get方法就返回null了，走field的获取

2022-06-05 13:44 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataField.java
> +        Object rs = methodGet();
我理解 get 方法可以做到没有判断的。在构造的时候应该就确定好取值方式，每次取属性都这么一大坨判断性能比较低下

2022-06-05 14:12 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +        Map<String, Integer> map = new HashMap<>();
不需要这个 map 也是可以实现这个功能的。用 map 浪费空间，性能也比较差。给个简单的不用 map 的例子：

```java
    public static Method getGetter(Class<?> clazz, String property, boolean isStaticCheck) {
        String isGet = BasicUtil.getIsGetter(property);
        String getter = BasicUtil.getGetter(property);
        return Arrays.stream(clazz.getMethods())
            .filter(method -> BasicUtil.isPublic(method) && method.getParameterTypes().length == 0)
            .flatMap(method -> getter.equals(method.getName())? Stream.of(new GetterCandicate(method, 1)):
                (isGet.equals(method.getName()) && method.getReturnType() == boolean.class)?
                    Stream.of(new GetterCandicate(method, 2)): Stream.empty())
            .max(GetterCandicate::getPriority)
            .orElse(null);
    }

    static class GetterCandicate {
        private Method method;
        private int priority;
    }
```

2022-06-05 14:12 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/lambda/QLambdaMethod.java
> +            throw this.errorReporter.report("GET_METHOD_VALUE_ERROR", "can not get method value: " + e.getMessage());
QLambda 在 dev 分支上已经都抛出异常了，再合一下，将这个异常抛出去，调用处 report 这个异常

2022-06-05 14:24 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/cache/LRUHashMap.java
> +import net.jcip.annotations.GuardedBy;
这是从哪里搬来的代码，注明一下。而且 GuardedBy Immutable 注解在我们代码里应该不生效的。简单的使用 LinkedHashMap 加个锁就行

2022-06-05 14:24 UTC, DQinYuan commented on src/test/resources/log4j.properties
>  log4j.appender.file.File=Test_LOG4j.log
不要搬以前的代码，没有用的话先删除掉

2022-06-07 15:55 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataMethodInvoke.java
> +public class DataMethodInvoke implements Value {
这个类记得记得删掉

2022-06-08 01:33 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataMethodInvoke.java
> +public class DataMethodInvoke implements Value {
fix

2022-06-08 12:07 UTC, DQinYuan requested changes

2022-06-08 12:07 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/cache/LRUCache.java
> +    private ReentrantReadWriteLock lock;
全部使用写锁, LRU读的时候也会改变数据结构

2022-06-08 12:39 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetFieldInstruction.java
> +                    getCacheFieldValue(qlOptions,(Class<?>) bean, bean, qRuntime);
补上用例

2022-06-15 16:55 UTC, DQinYuan requested changes

2022-06-15 16:55 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetMethodInstruction.java
> +            QLambda qLambda = new QLambdaMethod(methods, bean, qlOptions.enableAllowAccessPrivateMethod());
METHOD_NOT_EXIST 这种错误应该在这里提示，不应该放到后面

2022-06-15 16:55 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataFieldByGetAndSetField.java
> +            if (this.allowAccessPrivate || this.field.isAccessible()) {
这个判断感觉反了

2022-06-15 16:55 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataFieldByGetAndSetField.java
> +        } catch (Exception e) {
如果字段是私有的，这里会抛出什么异常？应该取的时候就将其判断好是否可以访问，不可访问的话直接在 GetField 是就抛出异常，而不是在后面 set 的时候

2022-06-15 16:55 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +        } else if (beforeReturnType.isAssignableFrom(afterReturnType)) {
getXxx 和返回值类型应该没有关系吧，除了 bool 以外

2022-06-16 02:06 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataFieldByGetAndSetField.java
> +            if (this.allowAccessPrivate || this.field.isAccessible()) {
fix

2022-06-16 02:13 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetMethodInstruction.java
> +            QLambda qLambda = new QLambdaMethod(methods, bean, qlOptions.enableAllowAccessPrivateMethod());
fix

2022-06-16 02:24 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataFieldByGetAndSetField.java
> +public class DataFieldByGetAndSetField implements LeftValue {
这个好

2022-06-16 02:56 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/DataFieldByGetAndSetField.java
> +        } catch (Exception e) {
fix

2022-06-16 03:58 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/member/MethodHandler.java
> +        } else if (beforeReturnType.isAssignableFrom(afterReturnType)) {
应该是以前老逻辑的校验兜底，如果QLE不能自己实现类的话，就不需要这段逻辑了，fix

2022-06-16 11:36 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetMethodInstruction.java
> +                    methods = PropertiesUtils.getMethod(bean, methodName, qlOptions.isAllowAccessPrivateMethod());
```java
class C {
      public static cc() {
           
      }
}

C c = new C();
c.cc();
```

2022-06-16 11:54 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/GetFieldInstruction.java
> +        if (!enableAllowAccessPrivateMethod || field.isAccessible()) {
!enableAllowAccessPrivateMethod && !field.isAccessible()
在这里就直接抛出错误。

2022-06-22 11:34 UTC, DQinYuan commented
LGTM

2022-06-22 11:35 UTC, DQinYuan approved these changes

2022-06-22 11:35 UTC, merged