Implicit conversion
alibaba/QLExpress pull request #199
Opened 2022-06-22 12:18 UTC by taokan

Implicit conversion

2022-07-02 16:04 UTC, DQinYuan commented
最好在 PR  里详细描述一下类型隐式转换的规则是什么

2022-07-02 16:14 UTC, DQinYuan requested changes

2022-07-02 16:14 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/InstanceConversion.java
> +            return type == boolean.class ? Boolean.FALSE : null;
确定 null 和 boolean 要有转换关系？

2022-07-02 16:14 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/InstanceConversion.java
> +        } else if (QLambda.class.isAssignableFrom(value.getClass()) && CacheUtil.isFunctionInterface(type)) {
QLambda 这个转换关系比较特殊，不需要 isAssignableFrom，只要是函数式接口就可以互转

2022-07-02 16:14 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/NumberConversion.java
> +                return (int) c.charAt(0);
字符串和数字最好还是不要有转换关系吧

2022-07-02 16:14 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/NumberConversion.java
> +        throw new QLTransferException("can not cast " + object.getClass().getName()
不要在这里抛出异常，也不需要额外定义异常，应该返回一个不可转换，由外层用 reporter 抛出异常，这样才能抛出用户可读的异常

2022-07-03 01:05 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/InstanceConversion.java
> +        } else if (QLambda.class.isAssignableFrom(value.getClass()) && CacheUtil.isFunctionInterface(type)) {
ok

2022-07-03 01:05 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/NumberConversion.java
> +                return (int) c.charAt(0);
行

2022-07-03 01:06 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/InstanceConversion.java
> +            return type == boolean.class ? Boolean.FALSE : null;
这个看诉求，以前是没有的，这次加不

2022-07-03 03:10 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/NumberConversion.java
> +        throw new QLTransferException("can not cast " + object.getClass().getName()
fix

2022-07-20 11:09 UTC, DQinYuan requested changes

2022-07-31 05:53 UTC, DQinYuan requested changes

2022-07-31 05:53 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/QLNumberToBigDecimalConvertChecker.java
> +}
规范：文件末尾应该有一个换行

2022-07-31 05:53 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/NumberConversion.java
> +    public static QLConvertResult castToNumber(Object object) {
这个方法感觉没有做任何实质上的事情，可以删除

2022-07-31 05:53 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/QLNumberConvertChecker.java
> +        QLConvertResult castToNumber = NumberConversion.castToNumber(value);
这个 .castToNumber 没有实质上的意义，可以删除

2022-07-31 05:53 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/TypeConvertChecker.java
> +public interface TypeConvertChecker<R, S, T> {
这里的 R 其实大家都一样，没必要用泛型吧

2022-07-31 05:53 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/TypeConvertChecker.java
> +    default boolean typeCheck(S source, T target){
如果有很多类都不需要实现这个方法的话，接口建议划分成两个，

一个 `TypeConverter`，其中只有 typeConvert 方法，另一个接口 `TypeChecker extends TypeConverter`，额外增加一个 `typeCheck` 方法

2022-07-31 05:53 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/QLNumberConvertChecker.java
> +        numberConvertMap.put(Byte.class,new QLNumberToByteConvertChecker());
从你的代码设计中看，QLNumberToByteConvertChecker 和 QLNumberConvertChecker 应该不是一个层面的东西，全放在一个包里看起来有点乱，应该按照层次放在不同的包里

2022-07-31 06:15 UTC, DQinYuan requested changes

2022-07-31 06:15 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/BooleanConversion.java
> +        if (object == null) {
以前 QLExpress 如果没有 null 和 bool 的互转的话，还是不要加了

2022-07-31 06:15 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/BooleanConversion.java
> +            return new QLConvertResult(QLConvertResultType.CAN_TRANS,(Boolean) object);
注意处理下小 boolean，虽然我们运行时不会有，但是用户的自定义函数有可能返回。

2022-07-31 06:15 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/QLFunctionConvertChecker.java
> +        return CacheUtil.isFunctionInterface(type);
type 是一个函数式接口，value 是 QLambda 类型才能转，不然下面的 typeReturn 方法会类型转换异常。貌似我之前的评论有误

2022-07-31 06:15 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/StringConversion.java
> +        String methodName = "toString";
toString 本来就是 Object 的成员方法，不需要反射调用

2022-07-31 06:15 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/StringConversion.java
> +    public static QLConvertResult trans(Object object) {
任意对象可转string这个感觉有点过于灵活了

2022-07-31 08:55 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/StringConversion.java
> +        String methodName = "toString";
这里没有实现tostring方法的话，如果用object.toString()不会报错，目前我这里的处理是不能转换

2022-07-31 08:55 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/QLFunctionConvertChecker.java
> +        return CacheUtil.isFunctionInterface(type);
ok

2022-07-31 08:58 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/BooleanConversion.java
> +        if (object == null) {
ok

2022-07-31 09:00 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/QLNumberToBigDecimalConvertChecker.java
> +}
ok

2022-07-31 09:11 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/TypeConvertChecker.java
> +    default boolean typeCheck(S source, T target){
最终调用的时候都要做check和convert的，如果拆开，实现TypeConverter的那些类怎么执行check呢

2022-07-31 09:11 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/TypeConvertChecker.java
> +public interface TypeConvertChecker<R, S, T> {
R不一样的

2022-07-31 09:11 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/QLNumberConvertChecker.java
> +        QLConvertResult castToNumber = NumberConversion.castToNumber(value);
ok

2022-07-31 09:15 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/BooleanConversion.java
> +            return new QLConvertResult(QLConvertResultType.CAN_TRANS,(Boolean) object);
ok

2022-07-31 09:16 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/StringConversion.java
> +        String methodName = "toString";
也就是说用户有显示实现了的才能转化

2022-07-31 09:24 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/QLNumberConvertChecker.java
> +        numberConvertMap.put(Byte.class,new QLNumberToByteConvertChecker());
好的，重新整理了下

2022-07-31 09:32 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/StringConversion.java
> +        String methodName = "toString";
ok

2022-08-07 01:45 UTC, DQinYuan requested changes

2022-08-07 02:08 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/Express4Runner.java
> +        userDefineFunction.put(name, new QFunctionInner(new QLambdaRegisterFunctional(functional)));
ok

2022-08-07 02:11 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/Express4Runner.java
> +        userDefineFunction.put(name, new QFunctionInner(new QLambdaRegisterRunnable(runnable)));
ok

2022-08-07 02:39 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/Express4Runner.java
> +//        List<Method> methods = PropertiesUtil.getMethod(object.getClass(), methodName, false);
开放出来

2022-08-07 07:48 UTC, DQinYuan approved these changes
先合并，剩下的后面再拉分支改

2022-08-07 07:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/MatchChecker.java
> +    ParametersConversion.QLMatchConverter typeReturn(Class<?> sourceType, Class<?> targetType);
枚举类挪到这个接口里吧

2022-08-07 07:48 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/convert/ParametersConversion.java
> +                    //TODO lingxiang
这个 Todo 具体写下原因

2022-08-07 07:49 UTC, merged