Boolean convertion fix
alibaba/QLExpress pull request #213
Opened 2022-10-23 08:23 UTC by taokan

测试用例

2022-11-02 12:35 UTC, DQinYuan commented on src/test/java/com/alibaba/qlexpress4/test/property/TestSuiteCaseForProperty.java
> +    public void test() throws IOException, URISyntaxException {
和 TestSuiteRunner 合并到一起，用于单独运行目录

2022-11-17 12:09 UTC, DQinYuan commented
QLNullConvertChecker 和 QLObjectConvertChecker 写反了

2022-11-17 12:11 UTC, DQinYuan commented
ArrayConversion 中可以删除 QLArrayAssignableConvertChecker

2022-11-17 12:22 UTC, DQinYuan requested changes

2022-11-17 12:22 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MemberHandler.java
>      private static QLImplicitMatcher doParamsConversion(Class<?>[] targetMatch, Class<?>[] goalMatch, int assignLevel,
不要对 QLParametersMatcher 进行反复的修改。考虑封装成成员方法

2022-11-27 03:12 UTC, taokan commented on src/test/resources/testsuite/java/implicit_convertion/test.ql
> +System.out.println(4);
删除了

2022-11-27 06:49 UTC, DQinYuan commented
> QLNullConvertChecker 和 QLObjectConvertChecker 写反了

2022-11-27 06:50 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/member/MemberHandler.java
>      private static QLImplicitMatcher doParamsConversion(Class<?>[] targetMatch, Class<?>[] goalMatch, int assignLevel,
这个先不改，后面我来想一想

2022-11-27 06:52 UTC, DQinYuan commented
点错了

2022-11-27 06:54 UTC, DQinYuan commented
LGTM

2022-11-27 06:54 UTC, DQinYuan approved these changes
LGTM

2022-11-27 06:55 UTC, merged