feat: use ConcurrentHashMap instead of HashMap with Sync(as HashTable…
alibaba/QLExpress pull request #221
Opened 2022-11-16 14:34 UTC by tiandankanfeng

use ConcurrentHashMap(AQS) instead of HashMap with Sync(as HashTable with low efficient) and allow user provide replace candidates based on ConcurrentHashMap.

2022-11-16 14:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/QLExpress?pullRequest=221) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/QLExpress?pullRequest=221) before we can accept your contribution.<br/><hr/>**Velpro** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/QLExpress?pullRequest=221) it.</sub>

2022-11-19 14:15 UTC, DQinYuan requested changes

2022-11-19 14:15 UTC, DQinYuan commented on pom.xml
> +        <dependency>
二方包应该要减少依赖，我们目前也在对 QLExpress 的依赖进行治理，所以不要引入其他二方库

2022-11-19 14:15 UTC, DQinYuan commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    public void setWrapCacheMap(ConcurrentHashMap<String, InstructionSet> map) {
如果要支持外部传入 map 的话，在构造函数传入是不是更好一点

2022-11-19 14:15 UTC, DQinYuan commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +        System.out.println(stopwatch.elapsed(TimeUnit.MILLISECONDS));
单元测试不要使用标准输出，历史上虽然有一些。但是我们会逐渐删除掉它们

2022-11-20 06:47 UTC, tiandankanfeng commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    public void setWrapCacheMap(ConcurrentHashMap<String, InstructionSet> map) {
是的，已更正.

2022-11-20 06:48 UTC, tiandankanfeng commented on pom.xml
> +        <dependency>
好的，已更换剔除.

2022-11-20 06:49 UTC, tiandankanfeng commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +        System.out.println(stopwatch.elapsed(TimeUnit.MILLISECONDS));
finish.

2022-11-20 06:49 UTC, tiandankanfeng commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +        System.out.println(stopwatch.elapsed(TimeUnit.MILLISECONDS));
finish.

2022-11-20 13:40 UTC, tiandankanfeng reviewed
最新的提交已经添加了构造传入以及清除了多余的pom依赖.

2022-11-20 13:44 UTC, tiandankanfeng commented on pom.xml
> +        <dependency>
> 二方包应该要减少依赖，我们目前也在对 QLExpress 的依赖进行治理，所以不要引入其他二方库

好的，已更换剔除.

2022-11-20 13:45 UTC, tiandankanfeng commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    public void setWrapCacheMap(ConcurrentHashMap<String, InstructionSet> map) {
> 如果要支持外部传入 map 的话，在构造函数传入是不是更好一点

是的，已更正.

2022-11-20 13:45 UTC, tiandankanfeng commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +        System.out.println(stopwatch.elapsed(TimeUnit.MILLISECONDS));
> 单元测试不要使用标准输出，历史上虽然有一些。但是我们会逐渐删除掉它们

已更改为使用 Assert.

2022-11-20 13:48 UTC, tiandankanfeng reviewed
add new Constructor.

2022-11-24 14:52 UTC, DQinYuan requested changes

2022-11-24 14:52 UTC, DQinYuan commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    private final ConcurrentHashMap<String, InstructionSet> expressInstructionSetCache;
实现默认用 ConcurrentHashMap，但是签名建议泛化。

比如 Map<String, InstructionSet> expressInstructionSetCache = new ConcurrentHashMap<>();

因为可能会有觉得 ConcurrentHashMap 也不是很好，或者觉得 HashMap 就够用了，依旧可以传递一个自定义的 map

2022-11-27 03:00 UTC, DQinYuan requested changes

2022-11-27 03:00 UTC, DQinYuan commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +            calculateTask(true, ctx);
最好能有一点耗时的 assert，不要纯做打印。

比如第一次执行耗时 t1
第二次执行耗时 t2

assertTrue(t2 < t1)

2022-11-27 04:21 UTC, tiandankanfeng commented on src/main/java/com/ql/util/express/ExpressRunner.java
>              parseResult = expressInstructionSetCache.get(expressString);
好的

2022-11-27 04:22 UTC, tiandankanfeng commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +            expressInstructionSetCache.putIfAbsent(expressString, parseResult = this.parseInstructionSet(expressString));
> 建议同上

已更正

2022-11-27 04:22 UTC, tiandankanfeng commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +        Assert.assertTrue(Objects.nonNull(new ExpressRunner()
> assertNonNull

done.

2022-11-27 04:22 UTC, tiandankanfeng commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +            calculateTask(true, ctx);
> 最好能有一点耗时的 assert，不要纯做打印。
> 
> 比如第一次执行耗时 t1 第二次执行耗时 t2
> 
> assertTrue(t2 < t1)

done

2022-11-27 04:22 UTC, tiandankanfeng commented
最新更改已提交上去了

2022-11-27 07:05 UTC, DQinYuan requested changes

2022-11-27 07:05 UTC, DQinYuan commented on src/main/java/com/ql/util/express/ExpressRunner.java
>              parseResult = expressInstructionSetCache.get(expressString);
如果用 computeIfAbsent, 这个 null 判断就不需要了，可以减少代码量
直接 parseResult = computeIfAbsent 即可

2022-11-27 07:05 UTC, DQinYuan commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +                        throw new RuntimeException(e);
最好不要在原来的异常上面包 RuntimeException.

可以考虑将 map 的 value 换成 Entry<InstructionSet, Exception>，computeIfAbsent 捕获异常后将其返回。
parseResult 如果拿到的是一个 exception，则直接抛出

2022-11-27 07:10 UTC, DQinYuan requested changes

2022-11-27 07:10 UTC, DQinYuan commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +        Assert.assertTrue(a < b);
确定 a > b 能稳定跑过吗？
首先变量的命名有点随意。
其次 calculateTask 中运行的脚本就只有一个宏("计算平均成绩")，过于简单，是否缓存对其执行事件影响不大，如果不能稳定跑过的，是否考虑设计一个稍复杂些的脚本来测试

2022-11-27 08:48 UTC, tiandankanfeng commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +                        throw new RuntimeException(e);
是的，感谢提醒，这是良好的编程方式

2022-11-27 08:48 UTC, tiandankanfeng commented on src/main/java/com/ql/util/express/ExpressRunner.java
>              parseResult = expressInstructionSetCache.get(expressString);
> 如果用 computeIfAbsent, 这个 null 判断就不需要了，可以减少代码量 直接 parseResult = computeIfAbsent 即可

done

2022-11-27 08:48 UTC, tiandankanfeng commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +                        throw new RuntimeException(e);
> 最好不要在原来的异常上面包 RuntimeException.
> 
> 可以考虑将 map 的 value 换成 Entry<InstructionSet, Exception>，computeIfAbsent 捕获异常后将其返回。 parseResult 如果拿到的是一个 exception，则直接抛出

是的，感谢提醒，这是良好的编程方式

2022-11-27 08:49 UTC, tiandankanfeng commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +        Assert.assertTrue(a < b);
> 确定 a > b 能稳定跑过吗？ 首先变量的命名有点随意。 其次 calculateTask 中运行的脚本就只有一个宏("计算平均成绩")，过于简单，是否缓存对其执行事件影响不大，如果不能稳定跑过的，是否考虑设计一个稍复杂些的脚本来测试

最新提交已经复杂化测试脚本以及规范了下命名.

2022-12-03 16:38 UTC, DQinYuan requested changes

2022-12-03 16:38 UTC, DQinYuan commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +    private long invokeCacheAndRecordRt(ExpressRunner runner, IExpressContext<String, Object> context) throws InterruptedException {
runner 传进来却没有使用，是不是写的有点问题？

2022-12-03 16:38 UTC, DQinYuan commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    public Map<String, InstructionSet> getExpressInstructionSetCache() {
暴露获取缓存指令的 map 的目的是什么？我们可以聊聊需求，或许有更好的方式解决

2022-12-03 17:06 UTC, tiandankanfeng commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +    private long invokeCacheAndRecordRt(ExpressRunner runner, IExpressContext<String, Object> context) throws InterruptedException {
> runner 传进来却没有使用，是不是写的有点问题？

这是旧的提交，新的提交已经去除这个方法了

2022-12-03 17:18 UTC, tiandankanfeng commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    public Map<String, InstructionSet> getExpressInstructionSetCache() {
> 暴露获取缓存指令的 map 的目的是什么？我们可以聊聊需求，或许有更好的方式解决
> 
> What is the purpose of exposing a map that gets cache instructions? We can talk about needs and maybe there's a better way

初始目的仅是为了测试，目前已去除暴露获取缓存的方法

2022-12-03 17:19 UTC, tiandankanfeng commented
最新的提交已经push

2022-12-11 14:39 UTC, DQinYuan requested changes

2022-12-11 14:39 UTC, DQinYuan commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +            if (parseResultEntry.getValue() instanceof Exception) {
这个判断方式是不是不太直观，本质上就是一个判 null，应该使用 parseResultEntry.getValue() ！= nulll

2022-12-11 14:39 UTC, DQinYuan commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    static final class MapEntry<K, V> implements Entry<K, V> {
Jdk 里有一个 SimpleEntry 可以用，没必要自己实现一个

2022-12-11 14:39 UTC, DQinYuan commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +        System.out.println(a);
单测里不要加 print

2022-12-11 14:39 UTC, DQinYuan commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +        Assert.assertTrue(a > b);
这里是为了表达 HashMap 比 ConcurrentMap 快吗?

2022-12-12 02:16 UTC, DQinYuan requested changes

2022-12-12 02:16 UTC, DQinYuan commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +            Entry<InstructionSet, Exception> parseResultEntry = expressInstructionSetCache.computeIfAbsent(
想了想，这里还是不要用 computeIfAbsent 了。错误脚本缓存起来不太合适，因为 addOperator 之类的操作可能会让原本出错的脚本变得正确

2022-12-12 16:14 UTC, DQinYuan requested changes

2022-12-12 16:14 UTC, DQinYuan commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    static final class MapEntry<K, V> implements Entry<K, V> {
把没有用的代码删掉

2022-12-12 16:28 UTC, DQinYuan requested changes

2022-12-12 16:28 UTC, DQinYuan commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +        long b = executeScriptWithTimeRecord(defaultRunner, context);
将 95 行和 96 行换个位置，你这个单测就过不了了。。。。b 比 a 快的本质原因不是因为脚本缓存。而是因为 QLExpress 目前有一些全局的对象复用，刚开始会慢一些，预热完后就快了，所以后运行的肯定比先运行的快（即使不是同一个 ExpressRunner 对象）。
建议不要额外写单元测试了，将原来的单元测试  com.ql.util.express.test.ExpressCacheTest#testScriptCache 加个 assert 优化下即可。

2022-12-13 05:02 UTC, tiandankanfeng commented on src/test/java/com/ql/util/express/test/ExpressCacheTest.java
> +        long b = executeScriptWithTimeRecord(defaultRunner, context);
> 

想了下，确实可以这么玩，如果想保留现有测试的话得再加个额外创建全局对象的runner，不是很有必要，我已经去除并且优化了下testScriptCache

2022-12-13 05:02 UTC, tiandankanfeng commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    static final class MapEntry<K, V> implements Entry<K, V> {
> 把没有用的代码删掉

done.

2022-12-13 05:56 UTC, tiandankanfeng commented
最新代码已提交.

2022-12-13 15:01 UTC, DQinYuan approved these changes
LGTM

2022-12-13 15:04 UTC, merged