Testcopy 4.0.0
alibaba/QLExpress pull request #230
Opened 2022-12-28 03:26 UTC by taokan

1.testsuitcase
2.list to array
3.support qlambda functional trans

2023-01-09 15:25 UTC, DQinYuan requested changes

2023-01-09 15:25 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/MethodInvokeInstruction.java
> +                QLImplicitLambda qlImplicitLambda = MethodHandler.Preferred.findMostSpecificLambda(type,
这里不需要这么复杂，map 里的 key 是唯一的，不需要考虑多态

2023-01-09 15:25 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/MethodInvokeInstruction.java
> +                convertResult = ParametersConversion.convert(params, type, qlImplicitLambda.getQLambdaInner().getLambdaParam()
类型转换在调用 QLambda 的内部已经做了，不需要转换了

2023-01-09 15:29 UTC, DQinYuan requested changes

2023-01-09 15:29 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/QLambdaInner.java
> +    public QLambdaDefinitionInner getLambdaDefinition() {
这个是内部进行类型转换用的，不要暴露给外部

2023-01-09 15:29 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/MethodInvokeInstruction.java
> +                    QLambdaInner qLambdaInnerMethod = (QLambdaInner) entry.getValue();
QLambda 的实现可不止 QLambdaInner，这会导致类型转换异常

2023-03-17 11:55 UTC, DQinYuan requested changes

2023-03-17 11:55 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/CastInstruction.java
> +        Object rs = qContext.pop();
用具体类型 Value 来接

2023-03-17 11:56 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/instruction/CastInstruction.java
> +        Object rs = qContext.pop();
list_cast_arr 跑不过的原因要具体研究下

2023-03-19 07:02 UTC, DQinYuan requested changes

2023-03-19 07:02 UTC, DQinYuan commented on src/test/resources/testsuite/java/implicit_convertion/functional_qlambda_implicit.ql
> +assert(TestFunctionToQLambda.runnable(r) == 18);
是不是理解反了？重点是测试 QLambda 到函数式接口的转换，函数式接口转 QLambda 感觉意义不太大

2023-03-19 07:02 UTC, DQinYuan commented on src/test/resources/testsuite/java/implicit_convertion/stream.ql
> +List b = (List) a;
stream 操作在哪里？

2023-04-01 03:51 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/Express4Runner.java
> +    private static final Log log = LogFactory.getLog(Express4Runner.class);
删除了

2023-04-01 04:48 UTC, taokan commented
这个分支按原子功能拆开

2023-05-05 12:08 UTC, closed without merging