feat: Enhanced for loop(foreach loop)
alibaba/QLExpress pull request #234
Opened 2023-02-01 03:16 UTC by jizhuozhi

Enhanced for loop through grammatical sugar solution

2023-02-01 03:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/QLExpress?pullRequest=234) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/QLExpress?pullRequest=234) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/QLExpress?pullRequest=234) it.</sub>

2023-02-01 03:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/QLExpress?pullRequest=234) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/QLExpress?pullRequest=234) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/QLExpress?pullRequest=234) it.</sub>

2023-03-04 23:58 UTC, taokan commented
你好，我们发现这个pr下面几个可以改进的地方，看看是否可以考虑改进下：
1.对于set，map等无法通过下标访问的结构存在问题
2.临时变量的管理需要优化，不建议在expressRunner里面，而且最好是没有临时变量
3.单测用例较少，没有断言

可以加我微信，我们新的版本发布后可以交流沟通 tkk33362

2023-03-05 03:45 UTC, jizhuozhi commented
对于问题1，Java中本身不存在对map的增强for循环，因此map不再考虑范围内。set确实是个问题，因为Java是强类型语言，因此在Javac中可以判断出变量的类型来决定是使用RandomAccess还是Iterator，但是在弱类型语言中因为所有对象只有运行时才能确定形状（Shape），因此无法仅通过在不添加新指令来完成对Iterator的支持。

同时兼顾问题2，如果要消除临时变量，意味着不论是RandomAccess还是Iterator都需要有新的统一的指令来创建栈对象，并且由这个栈对象来完成迭代动作的状态管理，但这确实消除了临时变量的使用。相较于栈对象，个人还是更喜欢使用槽位进行管理，因为不确定在后续过程中是否会出现栈的分叉（不过我还是会按照栈对象的方式来做）。

2023-03-05 04:05 UTC, jizhuozhi commented
对应的语法糖和指令如下所示，其中`LoadIter`为新引入的指令，它会对传入的集合进行包装，并将统一的迭代器对象(`hasNext`和`next`)压入栈

```
for (item: array) { ... } ->
iter = array.iterator(); while(iter.hasNext()) { item = iter.next(); ... } ->

Instructions:
  LoadAttr            array
  LoadIter            [1]
#1:
  MethodCall:hasNext  [1]
  GotoWithCondition   false #end
  MethodCall:next     [1]
  LoadAttr            item
  Operator:'='        [2]
  ...
  Goto #1
#end
```

2023-03-08 09:39 UTC, jizhuozhi commented
Hello, @taokan . 我已经尝试过使用栈对象而不是临时对象（对应虚拟机中是栈帧上的槽），但是不出意外的失败了。所以我依旧采用了与javac相同的临时参数的方式来实现。
```
         8: aload_1
         9: invokeinterface #10,  1           // InterfaceMethod java/util/List.iterator:()Ljava/util/Iterator;
        14: astore_2
        15: aload_2
        16: invokeinterface #16,  1           // InterfaceMethod java/util/Iterator.hasNext:()Z
        21: ifeq          34
        24: aload_2
        25: invokeinterface #22,  1           // InterfaceMethod java/util/Iterator.next:()Ljava/lang/Object;
        30: astore_3
        31: goto          15
```

2023-03-19 07:25 UTC, DQinYuan requested changes

2023-03-19 07:25 UTC, DQinYuan commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    private final AtomicLong tempAttrNo = new AtomicLong(0);
感觉是不是没有必要所有脚本都去竞争一个序号生成器？每个脚本自己生成自己的就行了吧

2023-03-19 07:36 UTC, jizhuozhi commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    private final AtomicLong tempAttrNo = new AtomicLong(0);
可以

2023-04-14 12:29 UTC, DQinYuan commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    public long nextTempAttrNo(){
存在线程安全问题

2023-04-15 15:12 UTC, jizhuozhi commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    public long nextTempAttrNo(){
emm…… https://github.com/alibaba/QLExpress/pull/234#discussion_r1141276081

I will revert it

2023-04-16 10:01 UTC, closed without merging

2023-04-16 14:42 UTC, DQinYuan commented on src/main/java/com/ql/util/express/ExpressRunner.java
> +    public long nextTempAttrNo(){
即使是每个 Runner 一个，也会存在并发访问，只是竞争会小一些

2023-04-17 03:00 UTC, jizhuozhi commented
非常不好意思，我想要确认下，这个序列号的作用是：在编译时通过序列号的方式生成临时参数来实现语法糖。现在会存在多线程同时编译同个脚本的情况吗？或者说同个Runner会被用于多个不同脚本的编译吗？

DQYuan ***@***.***>于2023年4月16日 周日22:43写道：

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/main/java/com/ql/util/express/ExpressRunner.java
> <https://github.com/alibaba/QLExpress/pull/234#discussion_r1167957474>:
>
> > @@ -114,6 +99,10 @@ public IOperateDataCache getOperateDataCache() {
>          return this.operateDataCacheThreadLocal.get();
>      }
>
> +    public long nextTempAttrNo(){
>
> 即使是每个 Runner 一个，也会存在并发访问，只是竞争会小一些
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alibaba/QLExpress/pull/234#discussion_r1167957474>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHN3C5WNEQC6ZHT4FEY42UDXBQAPPANCNFSM6AAAAAAUNGBIKQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>