修复 ==比较，其中一个参数为null，报错的bug
alibaba/QLExpress pull request #248
Opened 2023-03-17 05:52 UTC by lihongjuan1006

2023-03-17 05:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/QLExpress?pullRequest=248) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/QLExpress?pullRequest=248) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/QLExpress?pullRequest=248) it.</sub>

2023-03-26 13:54 UTC, DQinYuan requested changes

2023-03-26 13:54 UTC, DQinYuan commented on src/main/java/com/ql/util/express/instruction/op/OperatorEqualsLessMore.java
> +            if (!isCompareNullLessMoreAsFalse()) {
这个修改不对。如果打开了 isCompareNullLessMoreAsFalse 选项，会导致抛出异常。这个修改应该会导致部分单元测试无法通过

2023-03-26 13:56 UTC, muxinLi2023 commented
没明白，现在是其中一个为空，就报错了，那应该怎么修复这个问题呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: DQYuan ***@***.***&gt;
发送时间: 2023年3月26日 21:54
收件人: alibaba/QLExpress ***@***.***&gt;
抄送: muxinLi2023 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/QLExpress] 修复 ==比较，其中一个参数为null，报错的bug (PR #248)





 
@DQinYuan requested changes on this pull request.
 
 
In src/main/java/com/ql/util/express/instruction/op/OperatorEqualsLessMore.java:
 &gt; @@ -38,7 +38,7 @@ public static boolean executeInner(String opStr, Object obj1, Object obj2) throw            // 进行其他大小比较操作          if (obj1 == null || obj2 == null) { -            if (isCompareNullLessMoreAsFalse()) { +            if (!isCompareNullLessMoreAsFalse()) {  
这个修改不对。如果打开了 isCompareNullLessMoreAsFalse 选项，会导致抛出异常。这个修改应该会导致部分单元测试无法通过
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-03-27 01:30 UTC, muxinLi2023 commented on src/main/java/com/ql/util/express/instruction/op/OperatorEqualsLessMore.java
> +            if (!isCompareNullLessMoreAsFalse()) {
<img width="959" alt="image" src="https://user-images.githubusercontent.com/127938049/227819739-52f3b7f9-a60e-47f5-b719-64b68db9a552.png">

isCompareNullLessMoreAsFalse 你这个字段的含义不就是有一个为null时，返回false，现在没有返回false，而是报错抛异常了，应该怎么修复呢？大神给修复一下。

2023-06-24 00:19 UTC, taokan commented
QLExpressRunStrategy.compareNullLessMoreAsFalse 设置为true试试

2023-07-14 12:07 UTC, DQinYuan commented
误 compareNullLessMoreAsFalse 把当成反向开关了？

2023-07-14 12:07 UTC, closed without merging