Q lambda
alibaba/QLExpress pull request #254
Opened 2023-04-01 08:56 UTC by taokan

2023-04-13 15:56 UTC, DQinYuan requested changes

2023-04-13 15:56 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/paramchecker/QLLambdaFunctionalChecker.java
> +                || ((target == QLambda.class) && CacheUtil.isFunctionInterface(source));
函数式接口转 QLambda 意义不大

2023-04-13 15:56 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/runtime/data/checker/paramchecker/QLLambdaFunctionalChecker.java
> +                || ((target == QLambda.class) && CacheUtil.isFunctionInterface(source));
支持 QLambda 转函数式接口即可

2023-06-03 15:32 UTC, DQinYuan requested changes

2023-06-03 15:32 UTC, DQinYuan commented on src/test/resources/testsuite/java/cast/qlambda_functional.ql
> +QLambda lambda = (QLambda)r;
functional 不转 qlambda，这个用例应该可以删除了吧。删除一些跑不过的用例

2023-06-03 15:32 UTC, DQinYuan commented on src/test/resources/testsuite/java/cast/qlambda_implicit_functional.ql
> +QLambda lambda = (QLambda)f;
同上

2023-06-07 14:11 UTC, DQinYuan commented
建议补充一下更加能反映特性用途的测试用例，比如：

```
b = [1,2,3,4];
int[] c = b;
```

这种

2023-06-25 15:32 UTC, DQinYuan commented on src/test/resources/testsuite/java/cast/qlambda_functional.ql
> +QLambda lambda = (QLambda)r;
qlambda 不应该是一个脚本中可感知的概念，内部代表 callable

2023-06-26 12:37 UTC, taokan commented on src/test/resources/testsuite/java/cast/qlambda_functional.ql
> +QLambda lambda = (QLambda)r;
嗯，删除了

2023-06-28 14:37 UTC, merged