Safepoint
alibaba/QLExpress pull request #256
Opened 2023-04-09 06:38 UTC by taokan

whitelist,blacklist,sandbox

2023-04-13 16:16 UTC, DQinYuan requested changes

2023-04-13 16:16 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/Express4Runner.java
>          if (obj instanceof Class) {
用户永远都没有办法添加 Class 类中成员方法了。。。

addClassFunction 最好单独定义

2023-04-13 16:16 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/Express4Runner.java
> +        } catch (Exception e) {
不要 catch 直接抛出去吧。DebugInfo 不是用来干这个的

2023-04-13 16:16 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/security/SafePointStrategy.java
> +            systemStrategy.strategyBlackList = StrategyFactory.newStrategyBlackList(new HashMap<Class, String>() {{
可以定义成静态变量

2023-04-13 16:16 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/security/StrategySandBox.java
> +public abstract class StrategySandBox implements IStrategy {
没必要都搞个父类吧

2023-04-14 13:07 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/Express4Runner.java
> +        } catch (Exception e) {
直接抛异常。注释异常信息

2023-04-22 07:06 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/Express4Runner.java
>          if (obj instanceof Class) {
ok

2023-04-22 07:06 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/security/SafePointStrategy.java
> +            systemStrategy.strategyBlackList = StrategyFactory.newStrategyBlackList(new HashMap<Class, String>() {{
ok

2023-04-22 07:07 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/security/StrategySandBox.java
> +public abstract class StrategySandBox implements IStrategy {
这里我想的是用户可以自己定义实现sandbox相关的规则

2023-04-22 07:11 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/Express4Runner.java
> +        } catch (Exception e) {
改成void类型

2023-04-22 07:16 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/security/QLStrategyBlackList.java
> +        if(this.getBlackStrategyStructList().containsKey(iMethod.getClazz())){
// 必须将该选项设置为 true
QLExpressRunStrategy.setForbidInvokeSecurityRiskMethods(true);
// 有白名单设置时, 则黑名单失效
QLExpressRunStrategy.addSecureMethod(RiskBean.class, "secureMethod");

2023-04-22 07:18 UTC, taokan commented on src/main/java/com/alibaba/qlexpress4/security/QLStrategyBlackList.java
> +        if(this.getBlackStrategyStructList().containsKey(iMethod.getClazz())){
以前的运行期白名单是需要有class和methodName，这是参照以前的方式实现的

2023-05-05 15:55 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/security/StrategySandBox.java
> +public abstract class StrategySandBox implements IStrategy {
用户直接实现 IStrategy 不就好了

2023-05-05 16:01 UTC, DQinYuan requested changes

2023-05-05 16:01 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/security/QLStrategySandBox.java
> +        if (this.isSandBoxMode()) {
为啥在 Sandbox 里面还要判断 sandbox

2023-06-03 15:40 UTC, DQinYuan requested changes

2023-06-03 15:40 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/security/SafePointStrategy.java
> +    private IStrategyWhiteList strategyWhiteList;
这些系统固有策略直接作为静态属性放到 IStrategy 接口里就行了，没必要再搞一个子类

2023-06-03 15:40 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/QLOptions.java
> +        private SafePointStrategy safePointStrategy = SafePointStrategy.builder().defaultSystemStrategy();
没必要新建 SafePointStrategy 实例

2023-06-03 15:42 UTC, DQinYuan requested changes

2023-06-03 15:42 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/security/SafePointStrategy.java
> +public class SafePointStrategy implements IStrategy{
这个类没有存在的必要

2023-06-03 15:42 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/security/IStrategyBlackList.java
> +public interface IStrategyBlackList extends IRules {
为什么类层次搞得这么复杂？

2023-06-28 14:43 UTC, DQinYuan commented on src/main/java/com/alibaba/qlexpress4/QLOptions.java
> +    private final IStrategy strategySandBox;
这是什么？只需要给一个 IStrategy strategy，用户就可以自由配置了啊，不需要给三个

2023-09-09 01:51 UTC, DQinYuan commented
已实现

2023-09-09 01:51 UTC, closed without merging