修复issues-264的问题及优化计算溢出
alibaba/QLExpress pull request #266
Opened 2023-05-25 04:33 UTC by xiaolei55

2023-06-03 15:25 UTC, DQinYuan commented
#264

2023-06-03 15:27 UTC, DQinYuan commented on pom.xml
> +            <artifactId>commons-math3</artifactId>
不建议引入新的依赖，可以参考原理编写

2023-06-05 14:24 UTC, xiaolei55 commented on pom.xml
> +            <artifactId>commons-math3</artifactId>
已将新依赖移除

2023-06-09 11:55 UTC, DQinYuan requested changes

2023-06-09 11:55 UTC, DQinYuan commented on src/test/java/com/ql/util/express/bugfix/PreciseCalculationTest.java
> +		System.out.println(result);
用 assert 断言结果，不要只是打印

2023-08-04 11:42 UTC, pymBupt commented
在QLExpress 4.0版本中支持，同时增加开关可选择开启

2023-08-04 12:26 UTC, closed without merging

2023-08-22 10:17 UTC, zuixinwenyu commented
现在这个问题有办法解决吗