Issue295
alibaba/QLExpress pull request #302
Opened 2023-11-26 07:26 UTC by taokan

2023-12-09 03:14 UTC, DQinYuan commented
#295

2023-12-09 03:23 UTC, DQinYuan requested changes

2023-12-09 03:23 UTC, DQinYuan commented on src/main/java/com/ql/util/express/config/QLExpressRunStrategy.java
> +    private static final Set<String> SECURE_RISK_CONSTRUCTOR_LIST = new HashSet<>();
可以考虑默认加一些常见不安全类的黑名单, 比如之前 issue 里提的那个, 可以咨询下安全

2023-12-09 03:23 UTC, DQinYuan commented on src/main/java/com/ql/util/express/config/QLExpressRunStrategy.java
> +    private static boolean forbidInvokeSecurityRiskConstructors = false;
这两个这一次直接默认为 true 吧

2023-12-09 03:23 UTC, DQinYuan commented on src/test/java/com/ql/util/express/bugfix/InvokeSecurityRiskConstructorsTest.java
> +                System.out.println(result);
使用 assert 写单元测试, 而不是 print

2023-12-09 03:23 UTC, DQinYuan commented
我周一去找安全要一个构造函数名单

2023-12-11 11:19 UTC, taokan commented on src/test/java/com/ql/util/express/bugfix/InvokeSecurityRiskConstructorsTest.java
> +                Object result = expressRunner.execute(express, context, null, true, false, 1000);
ok

2023-12-24 12:50 UTC, DQinYuan commented
本地跑一下单元测试, 安全策略默认为 true, 会不会有单测跑不过

2024-01-07 13:55 UTC, DQinYuan requested changes

2024-01-07 13:55 UTC, DQinYuan commented on src/test/java/com/ql/util/express/bugfix/InvokeSecurityRiskConstructorsTest.java
> +    private boolean preForbidInvokeSecurityRiskConstructors;
这里取出来是为了在 after 中恢复吗?但是并没有看到 `@After`

2024-01-07 13:55 UTC, DQinYuan commented on src/test/java/com/ql/util/express/bugfix/InvokeSecurityRiskConstructorsTest.java
> +        //QLExpressRunStrategy.addRiskSecureConstructor(InvokeSecurityRiskConstructorsTest.class);
只测试了白名单的有效性, 没有测试黑名单的有效性

2024-01-07 13:55 UTC, DQinYuan commented on src/main/java/com/ql/util/express/config/QLExpressRunStrategy.java
> +        SECURITY_RISK_METHOD_LIST.add("org.springframework.jndi.JndiLocatorDelegate.lookup");
SECURE_RISK_CONSTRUCTOR_LIST 黑名单记得加默认值

2024-02-26 11:50 UTC, DQinYuan requested changes

2024-02-26 11:50 UTC, DQinYuan commented on src/main/java/com/ql/util/express/config/QLExpressRunStrategy.java
> +        addRiskSecureConstructor(java.lang.ProcessBuilder.class);
放可以 new 的类，比如 issue 里的。这里的类大多都new不了

2024-03-31 06:55 UTC, DQinYuan requested changes

2024-03-31 06:55 UTC, DQinYuan commented on src/test/java/com/ql/util/express/bugfix/InvokeSecurityRiskConstructorsTest.java
> +                System.out.println(e.getCause());
单元测试中不要有 print

2024-03-31 07:24 UTC, DQinYuan commented
LGTM

2024-03-31 07:38 UTC, DQinYuan approved these changes
LGTM

2024-03-31 07:44 UTC, merged