fix comment in import#337
alibaba/QLExpress pull request #340
Opened 2024-08-12 07:35 UTC by jackie-coming

修复首行注释解析问题

2024-08-12 07:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/QLExpress?pullRequest=340) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/QLExpress?pullRequest=340) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/QLExpress?pullRequest=340) it.</sub>

2024-08-12 07:38 UTC, jackie-coming commented
> 修复首行注释解析问题

#337

2024-08-12 08:07 UTC, DQinYuan commented
#337

2024-08-14 15:39 UTC, DQinYuan requested changes

2024-08-14 15:39 UTC, DQinYuan commented on src/test/java/com/ql/util/express/issue/Issue337CommentInImportTest.java
> +        System.out.println(result);
在单元测试中不要打印内容到标准输出

2024-08-14 15:39 UTC, DQinYuan commented on src/test/java/com/ql/util/express/issue/Issue337CommentInImportTest.java
> +        TestCase.assertEquals("successful", result);
junit4 一般习惯用 Assert.assertEquals

TestCase 在 junit3 中用的多一些, 本项目主要使用 junit4

2024-08-14 15:39 UTC, DQinYuan commented on src/test/java/com/ql/util/express/issue/Issue337CommentInImportTest.java
> +        String express = ""
在单元测试中, 尽量使用最小复现问题的用例, 不需要这么复杂.

对于这个问题, 只需要一行注释 + import 即可复现, 不需要搞这个复杂.

举例:

```
String express = "/** 注释 **/;import java.util.ArrayList;";
```

2024-08-14 15:51 UTC, DQinYuan commented
![image](https://github.com/user-attachments/assets/7e343cc5-a42b-4997-811c-df807a17f26e)

有个单测在本地执行 `mvn test` 的时候不通过, 顺便也修下吧

2024-08-15 02:24 UTC, jackie-coming commented
> ![image](https://private-user-images.githubusercontent.com/23725000/357894550-7e343cc5-a42b-4997-811c-df807a17f26e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODY4MDAsIm5iZiI6MTcyMzY4NjUwMCwicGF0aCI6Ii8yMzcyNTAwMC8zNTc4OTQ1NTAtN2UzNDNjYzUtYTQyYi00OTk3LTgxMWMtZGY4MDdhMTdmMjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAxNDgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYTdkM2I4YWI0ZTA2NzViODg4YTZiYmRkYjgwM2U2NzhlZWJiZjIzNjE4N2Y2YmEwYTA4Zjk1NmY0YjQ1ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WcFg-CtXqkYA6E2mRMEIN657o5DlZKohMp3250K6FKw)
> 
> 有个单测在本地执行 `mvn test` 的时候不通过, 试一下, 如果你那面也不通过, 顺便也修下吧

是有问题，我看下

2024-08-15 06:11 UTC, jackie-coming commented
> ![image](https://private-user-images.githubusercontent.com/23725000/357894550-7e343cc5-a42b-4997-811c-df807a17f26e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDIzNjksIm5iZiI6MTcyMzcwMjA2OSwicGF0aCI6Ii8yMzcyNTAwMC8zNTc4OTQ1NTAtN2UzNDNjYzUtYTQyYi00OTk3LTgxMWMtZGY4MDdhMTdmMjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA2MDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZDZhODdmZjgxODI0MjEyZGUyNTM4Y2Y1NGJlMjRhMWJkZGI2MDIzMjkyMGEyNTNjZTY2MjQyZmU5MjE3OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GS7ftn3BjhQJ6A0jWcp0TWtQRRo8JnQlnsT7z4nCeBQ)
> 
> 有个单测在本地执行 `mvn test` 的时候不通过, 试一下, 如果你那面也不通过, 顺便也修下吧

试了最新的v3.3.3 代码，也有这个问题，同时只有在maven test的时候才会复现，我新开个issue跟一下这个问题吧。
![Uploading image.png…]()

2024-08-18 14:11 UTC, DQinYuan commented
@jackie-coming 这个问题在 master 应该也存在很久了, 看起来像是测试框架引发的问题, 导致反射取不到字段

2024-08-18 14:11 UTC, DQinYuan approved these changes
LGTM

2024-08-18 14:13 UTC, DQinYuan commented
@jackie-coming  记得再开个 issue 跟这个问题,我先合并了

2024-08-18 14:13 UTC, merged