fix IllegalAccessException
alibaba/QLExpress pull request #346
Opened 2024-08-20 02:27 UTC by jackie-coming

修复测试框架没有权限访问报错的问题

2024-08-20 02:27 UTC, jackie-coming commented
> 修复测试框架没有权限访问报错的问题

#342

2024-08-20 08:20 UTC, jackie-coming commented
> 修复测试框架没有权限访问报错的问题

原因：1、本地debug mvn test 可以发现junit4框架调用了System.setOut()，将System.out赋值为
ConsoleOutputCapture$ForwardingPrintStream。 所有调用System.out的地方都会有这个问题。
![image](https://github.com/user-attachments/assets/e159d39d-76fa-4232-a124-f5b83f367bea)

2、ConsoleOutputCapture$ForwardingPrintStream中的println为private,所以执行mvn test时，报
java.lang.IllegalAccessException: Class com.ql.util.express.instruction.op.OperatorMethod can not access a member of class org.apache.maven.surefire.api.report.ConsoleOutputCapture$ForwardingPrintStream with modifiers "public"
![image](https://github.com/user-attachments/assets/ab3aab8f-2bf2-4dbf-9c60-f5f088e6f42e)


解决方案：1、调用method.setAccessible(true);允许访问private 修饰的成员、方法。 比如com.ql.util.express.instruction.op.OperatorMethod#executeInner
![image](https://github.com/user-attachments/assets/6c50e583-127d-44d4-af73-42a9cc3a11cd)

2、继承PrintStream，手动调用System.setOut()
![image](https://github.com/user-attachments/assets/b9a9868e-7deb-4380-8402-b553f5e14b6a)

2024-08-25 08:24 UTC, DQinYuan requested changes

2024-08-25 08:24 UTC, DQinYuan commented on src/test/java/com/ql/util/express/test/ForFlowFunctionTest.java
> +        System.setOut(new MyPrintStream01(outContent));
单测还是尽量精简一些，可以考虑直接将原第19行的 `System.out` 换成 `new PrintStream(new ByteArrayOutputStream())`，跟你这里的修改应该是等价的

2024-08-26 02:25 UTC, jackie-coming commented on src/test/java/com/ql/util/express/test/ForFlowFunctionTest.java
> +        System.setOut(new MyPrintStream01(outContent));
done

2024-08-31 10:31 UTC, DQinYuan approved these changes
LGTM

2024-08-31 10:32 UTC, merged